name: CI
on: [push]
jobs:
    validate:
        runs-on: ubuntu-latest
        container:
            image: ghcr.io/steevanb/php-dev-ops:ci
        steps:
            -
                name: Checkout repository
                uses: actions/checkout@v4
            -
                name: Composer cache
                uses: actions/cache@v3
                with:
                    path: vendor
                    key: composer-${{ hashFiles('composer.json') }}
                    restore-keys: composer-${{ hashFiles('composer.json') }}
            - run: composer install --no-dev --optimize-autoloader --ansi
            - run: bin/console cache:warmup --ansi
            - run: bin/ci/validate --theme=summary
